version: "3.8"
services:
  db:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - "5666:5432"
    volumes:
      - /Users/macbook/Desktop/text/volume/data:/var/lib/postgresql/data
    restart: always
    command:
      postgres
      -c max_connections=1024
      # -c logging_collector=on
      # -c log_connections=on
    networks:
      - postgres_bridge

networks:
  postgres_bridge:
    driver: bridge
